### ISSUE TITLE
一些免版税（免版权）音乐网站

### ISSUE THREAD

**Issue by YangXiaoguozi** [Youmiel/CC-Music-List#2]
pixabay.com/music
许可[pixabay.com](https://pixabay.com/service/license/)
www.videvo.net/royalty-free-music
许可[videvo.net](https://help.videvo.net/category/6-licensing)
www.audiolibrary.com.co
许可[www.audiolibrary.com.co](https://twitter.com/ytaudiolibrary/)
mixkit.co/free-stock-music
许可[mixkit.co](https://mixkit.co/license/)

**Comment by Youmiel** [comment]
感谢issue! 不过royalty free(免版税)和免费的概念还是不一样，免版税的直观理解就是“一次付费，多次使用”，这个区别我之后得在README里面强调一下。目前不打算在列表中整理免版税音乐，**后续有机会的话**，我会在新列表中记录免版税音乐。

大致看下来，issue中四个网站都有部分音乐是免费的，稍后会更新列表。
